
# Run continuous integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x', '20.x']

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      #- uses: actions/checkout@v4
      #- name: Use Node.js
      #  uses: actions/setup-node@v4
      #  with:
      #    node-version: '20.x'

      - name: Install dependencies
        run: npm install
      - run: npm run build --if-present


      # Generate BOM file and upload to Dependency-Track
      - name: Install BOM generating tool (cyclonedx-bom)
        run: 'npm install --global @cyclonedx/cyclonedx-npm'
      - name: Generate BOM file
        run: cyclonedx-npm --output-file bom.json --output-format JSON        
#      - name: Upload BOM file to Dependency-Track
#        run: |
#          curl -X "POST" http://antovski.ddns.net:8091/api/v1/bom -H 'Content-Type: multipart/form-data' -H "X-Api-Key: odt_jwqMzLAEplZlA0WHat9lps0UC40p99qb" -F "autoCreate=true" -F "projectName=vscode-remote-try-node" -F "project=7044d259-c8ed-475b-8d69-ff30f0882dbf" -F "projectVersion=4.0" -F "bom=@./bom.json"
      - name: SBOM zu DependencyTrack senden
        uses: DependencyTrack/gh-upload-sbom@v3
        with:
          serverHostname: 'http://antovski.ddns.net:8091/api/v1/bom'
          port: 8091
          protocol: 'http'
          apiKey: 'odt_jwqMzLAEplZlA0WHat9lps0UC40p99qb'
          projectName: 'Example Project'
          projectVersion: '1.0'
          bomFilename: "bom.json"
          autoCreate: true
          parentName: 'Example Parent'
          parentVersion: 'master.v1'        







          #curl -X "POST" http://antovski.ddns.net:8091/api/v1/bom -H 'Content-Type:multipart/form-data' -H 'X-Api-Key:odt_jwqMzLAEplZlA0WHat9lps0UC40p99qb' -F 'project=aa9e0336-d990-4015-bde7-27c91ff23827' -F 'bom=@./bom.json'




